const VOC_resolutions = [
    { q:"Organizado/a", a:"organized", e:"📅" },
    { q:"Comprar", a:"buy", e:"🛒" },
    { q:"Hacer", a:"do", e:"✅" },
    { q:"Ganar", a:"earn", e:"💰" },
    { q:"Conseguir", a:"get", e:"🎯" },

    { q:"Ponerse en forma", a:"get in shape", e:"💪" },
    { q:"Tener una entrevista", a:"have an interview", e:"💼" },
    { q:"Mejorar tu dieta", a:"improve your diet", e:"🥗" },
    { q:"Mejorar tu relación", a:"improve your relationship", e:"❤️" },
    { q:"Inscribirse a un gimnasio", a:"join a gym", e:"🏋️" },

    { q:"Perder peso", a:"lose weight", e:"⚖️" },
    { q:"Hacer", a:"make", e:"🛠️" },
    { q:"Conocer a alguien nuevo", a:"meet someone new", e:"🤝" },
    { q:"Correr un maratón", a:"run a marathon", e:"🏃" },
    { q:"Ahorrar dinero", a:"save money", e:"🏦" },

    // Vocabulario adicional
    { q:"Dejar de fumar", a:"quit smoking", e:"🚭" },
    { q:"Comer más saludable", a:"eat healthier", e:"🍎" },
    { q:"Hacer ejercicio regularmente", a:"exercise regularly", e:"🏃‍♂️" },
    { q:"Aprender inglés", a:"learn English", e:"🇬🇧" },
    { q:"Aprender un nuevo idioma", a:"learn a new language", e:"🗣️" },
    { q:"Leer más libros", a:"read more books", e:"📚" },
    { q:"Estudiar más", a:"study more", e:"📖" },
    { q:"Conseguir un mejor trabajo", a:"get a better job", e:"💼" },
    { q:"Encontrar trabajo", a:"find a job", e:"🔍" },
    { q:"Obtener un ascenso", a:"get a promotion", e:"📈" },
    { q:"Viajar más", a:"travel more", e:"✈️" },
    { q:"Pasar más tiempo con la familia", a:"spend more time with family", e:"👨‍👩‍👧‍👦" },
    { q:"Ser más puntual", a:"be more punctual", e:"⏰" },
    { q:"Reducir el estrés", a:"reduce stress", e:"🧘" },
    { q:"Dormir mejor", a:"sleep better", e:"😴" },
    { q:"Beber más agua", a:"drink more water", e:"💧" },
    { q:"Ahorrar energía", a:"save energy", e:"⚡" },
    { q:"Gastar menos dinero", a:"spend less money", e:"💸" },
    { q:"Ser más productivo", a:"be more productive", e:"🚀" },
    { q:"Comenzar un nuevo pasatiempo", a:"start a new hobby", e:"🎨" },
    { q:"Aprender a cocinar", a:"learn to cook", e:"👨‍🍳" },
    { q:"Mantener la habitación limpia", a:"keep my room tidy", e:"🧹" },
    { q:"Usar menos el teléfono", a:"use my phone less", e:"📵" },
    { q:"Ver menos televisión", a:"watch less TV", e:"📺" },
    { q:"Ser más amable", a:"be kinder", e:"😊" }
];