const REGULAR_VERBS = [
    { base:"walk",     past:"walked",   participle:"walked",    spanish:"caminar",      e:"🚶" },
    { base:"talk",     past:"talked",   participle:"talked",    spanish:"hablar/charlar",e:"💬" },
    { base:"play",     past:"played",   participle:"played",    spanish:"jugar/tocar",  e:"🎮" },
    { base:"watch",    past:"watched",  participle:"watched",   spanish:"ver/mirar",    e:"📺" },
    { base:"work",     past:"worked",   participle:"worked",    spanish:"trabajar",     e:"💼" },
    { base:"call",     past:"called",   participle:"called",    spanish:"llamar",       e:"📞" },
    { base:"ask",      past:"asked",    participle:"asked",     spanish:"preguntar",    e:"❓" },
    { base:"answer",   past:"answered", participle:"answered",  spanish:"responder",    e:"✅" },
    { base:"visit",    past:"visited",  participle:"visited",   spanish:"visitar",      e:"🏠" },
    { base:"cook",     past:"cooked",   participle:"cooked",    spanish:"cocinar",      e:"🍳" },
    { base:"clean",    past:"cleaned",  participle:"cleaned",   spanish:"limpiar",      e:"🧹" },
    { base:"open",     past:"opened",   participle:"opened",    spanish:"abrir",        e:"🚪" },
    { base:"close",    past:"closed",   participle:"closed",    spanish:"cerrar",       e:"🔒" },
    { base:"start",    past:"started",  participle:"started",   spanish:"empezar",      e:"▶️" },
    { base:"finish",   past:"finished", participle:"finished",  spanish:"terminar",     e:"🏁" },
    { base:"help",     past:"helped",   participle:"helped",    spanish:"ayudar",       e:"🤝" },
    { base:"love",     past:"loved",    participle:"loved",     spanish:"amar",         e:"❤️" },
    { base:"like",     past:"liked",    participle:"liked",     spanish:"gustar",       e:"👍" },
    { base:"hate",     past:"hated",    participle:"hated",     spanish:"odiar",        e:"😠" },
    { base:"need",     past:"needed",   participle:"needed",    spanish:"necesitar",    e:"📋" },
    { base:"want",     past:"wanted",   participle:"wanted",    spanish:"querer",       e:"🌟" },
    { base:"use",      past:"used",     participle:"used",      spanish:"usar",         e:"🔧" },
    { base:"try",      past:"tried",    participle:"tried",     spanish:"intentar",     e:"💪" },
    { base:"study",    past:"studied",  participle:"studied",   spanish:"estudiar",     e:"📚" },
    { base:"learn",    past:"learned",  participle:"learned",   spanish:"aprender",     e:"🎓" },
    { base:"travel",   past:"traveled", participle:"traveled",  spanish:"viajar",       e:"✈️" },
    { base:"dance",    past:"danced",   participle:"danced",    spanish:"bailar",       e:"💃" },
    { base:"paint",    past:"painted",  participle:"painted",   spanish:"pintar",       e:"🎨" },
    { base:"jump",     past:"jumped",   participle:"jumped",    spanish:"saltar",       e:"🦘" },
    { base:"push",     past:"pushed",   participle:"pushed",    spanish:"empujar",      e:"🤜" },
    { base:"pull",     past:"pulled",   participle:"pulled",    spanish:"jalar",        e:"🤛" },
    { base:"move",     past:"moved",    participle:"moved",     spanish:"mover",        e:"📦" },
    { base:"stop",     past:"stopped",  participle:"stopped",   spanish:"parar",        e:"🛑" },
    { base:"wait",     past:"waited",   participle:"waited",    spanish:"esperar",      e:"⏳" },
    { base:"follow",   past:"followed", participle:"followed",  spanish:"seguir",       e:"👣" },
    { base:"miss",     past:"missed",   participle:"missed",    spanish:"extrañar/fallar",e:"😔" },
    { base:"change",   past:"changed",  participle:"changed",   spanish:"cambiar",      e:"🔄" },
    { base:"smile",    past:"smiled",   participle:"smiled",    spanish:"sonreír",      e:"😊" },
    { base:"arrive",   past:"arrived",  participle:"arrived",   spanish:"llegar",       e:"🏁" },
    { base:"listen",   past:"listened", participle:"listened",  spanish:"escuchar",     e:"👂" },
    { base:"show",     past:"showed",   participle:"showed",    spanish:"mostrar",      e:"📢" },
    { base:"create",   past:"created",  participle:"created",   spanish:"crear",        e:"✨" },
    { base:"remember", past:"remembered",participle:"remembered",spanish:"recordar",    e:"🧠" },
    { base:"decide",   past:"decided",  participle:"decided",   spanish:"decidir",      e:"🎯" },
    { base:"plan",     past:"planned",  participle:"planned",   spanish:"planear",      e:"📅" },
    { base:"live",     past:"lived",    participle:"lived",     spanish:"vivir",        e:"🏡" },
    { base:"accept",   past:"accepted", participle:"accepted",  spanish:"aceptar",      e:"✅" },
    { base:"enjoy",    past:"enjoyed",  participle:"enjoyed",   spanish:"disfrutar",    e:"😁" },
    { base:"share",    past:"shared",   participle:"shared",    spanish:"compartir",    e:"🤲" },
    { base:"save",     past:"saved",    participle:"saved",     spanish:"guardar/salvar",e:"💾" },
];
