const VOC_daily_routine = [
    { q:"Despertarse", a:"Wake up", e:"⏰" },
    { q:"Levantarse", a:"Get up", e:"🛏️" },
    { q:"Tender la cama", a:"Make the bed", e:"🛏️" },
    { q:"Ducharse", a:"Take a shower", e:"🚿" },
    { q:"Bañarse", a:"Take a bath", e:"🛁" },
    { q:"Lavarse la cara", a:"Wash my face", e:"🧼" },
    { q:"Cepillarse los dientes", a:"Brush my teeth", e:"🪥" },
    { q:"Peinarse", a:"Comb my hair", e:"🪮" },
    { q:"Vestirse", a:"Get dressed", e:"👕" },
    { q:"Desayunar", a:"Have breakfast", e:"🍳" },
    { q:"Tomar café", a:"Drink coffee", e:"☕" },
    { q:"Ir a la escuela", a:"Go to school", e:"🏫" },
    { q:"Ir a la universidad", a:"Go to university", e:"🎓" },
    { q:"Ir a trabajar", a:"Go to work", e:"💼" },
    { q:"Estudiar", a:"Study", e:"📚" },
    { q:"Asistir a clases", a:"Attend classes", e:"🏫" },
    { q:"Tomar notas", a:"Take notes", e:"📝" },
    { q:"Almorzar", a:"Have lunch", e:"🍽️" },
    { q:"Comer", a:"Eat", e:"🍔" },
    { q:"Beber agua", a:"Drink water", e:"💧" },
    { q:"Llegar a casa", a:"Get home", e:"🏠" },
    { q:"Terminar la escuela", a:"Finish school", e:"🎒" },
    { q:"Terminar de trabajar", a:"Finish work", e:"📂" },
    { q:"Hacer la tarea", a:"Do homework", e:"📖" },
    { q:"Leer", a:"Read", e:"📚" },
    { q:"Escuchar música", a:"Listen to music", e:"🎧" },
    { q:"Ver televisión", a:"Watch TV", e:"📺" },
    { q:"Jugar videojuegos", a:"Play video games", e:"🎮" },
    { q:"Usar la computadora", a:"Use the computer", e:"💻" },
    { q:"Hacer ejercicio", a:"Exercise", e:"🏃" },
    { q:"Salir a caminar", a:"Go for a walk", e:"🚶" },
    { q:"Correr", a:"Run", e:"🏃‍♂️" },
    { q:"Preparar la cena", a:"Prepare dinner", e:"👨‍🍳" },
    { q:"Cenar", a:"Have dinner", e:"🍝" },
    { q:"Relajarse", a:"Relax", e:"😌" },
    { q:"Hablar con amigos", a:"Talk to friends", e:"🗣️" },
    { q:"Revisar el teléfono", a:"Check my phone", e:"📱" },
    { q:"Ir a la cama", a:"Go to bed", e:"🛏️" },
    { q:"Dormirse", a:"Go to sleep", e:"😴" },
    { q:"Soñar", a:"Dream", e:"💭" },
];
