const VOC_personal_objects = [
    { q:"Llaves", a:"Keys", e:"🔑" },
    { q:"Gafas de sol", a:"Sunglasses", e:"🕶️" },
    { q:"Espejo", a:"Mirror", e:"🪞" },
    { q:"Guantes", a:"Gloves", e:"🧤" },
    { q:"Goma de mascar", a:"Chewing gum", e:"🍬" },
    { q:"Linterna", a:"Flashlight", e:"🔦" },
    { q:"Pañuelos", a:"Tissues", e:"🤧" },
    { q:"Foto", a:"Photo", e:"📷" },
    { q:"Estampillas", a:"Stamps", e:"📮" },
    { q:"Anteojos", a:"Glasses", e:"👓" },
    { q:"Carné de identidad", a:"Identity card", e:"🪪" },
    { q:"Reloj", a:"Watch", e:"⌚" },
    { q:"Sombrilla", a:"Umbrella", e:"☂️" },
    { q:"Cepillo para el cabello", a:"Hairbrush", e:"🪮" },
    { q:"Billetera", a:"Wallet", e:"👛" },
    { q:"Dulce", a:"Candy", e:"🍭" },
    { q:"Monedero", a:"Change purse", e:"👝" },
    { q:"Peine", a:"Comb", e:"🪮" },
    { q:"Tableta", a:"Tablet", e:"📱" },
    { q:"Teléfono", a:"Phone", e:"📱" },
    { q:"Celular", a:"Cell phone", e:"📱" },
    { q:"Computadora portátil", a:"Laptop", e:"💻" },
    { q:"Mochila", a:"Backpack", e:"🎒" },
    { q:"Bolso", a:"Bag", e:"👜" },
    { q:"Libro", a:"Book", e:"📚" },
    { q:"Cuaderno", a:"Notebook", e:"📓" },
    { q:"Lápiz", a:"Pencil", e:"✏️" },
    { q:"Bolígrafo", a:"Pen", e:"🖊️" },
    { q:"Borrador", a:"Eraser", e:"🩹" },
    { q:"Regla", a:"Ruler", e:"📏" },
    { q:"Tijeras", a:"Scissors", e:"✂️" },
    { q:"Botella de agua", a:"Water bottle", e:"🧴" },
    { q:"Auriculares", a:"Headphones", e:"🎧" },
    { q:"Cargador", a:"Charger", e:"🔌" },
    { q:"Dinero", a:"Money", e:"💵" },
    { q:"Monedas", a:"Coins", e:"🪙" },
    { q:"Pasaporte", a:"Passport", e:"📘" },
    { q:"Tarjeta de crédito", a:"Credit card", e:"💳" },
    { q:"Llave USB", a:"USB drive", e:"💾" },
];
