const VOC_clothes = [
    { q:"Cinturón", a:"Belt", e:"🩳" },
    { q:"Corbata", a:"Tie", e:"👔" },
    { q:"Collar", a:"Necklace", e:"📿" },
    { q:"Pulsera", a:"Bracelet", e:"📿" },
    { q:"Pantalones", a:"Pants", e:"👖" },
    { q:"Camiseta/Playera", a:"T-shirt", e:"👕" },
    { q:"Camisa", a:"Shirt", e:"👔" },
    { q:"Blusa", a:"Blouse", e:"👚" },
    { q:"Pendientes/Aretes", a:"Earrings", e:"💎" },
    { q:"Botas", a:"Boots", e:"🥾" },
    { q:"Zapatos", a:"Shoes", e:"👞" },
    { q:"Sandalias", a:"Sandals", e:"👡" },
    { q:"Tenis/Deportivos", a:"Sneakers", e:"👟" },
    { q:"Abrigo", a:"Coat", e:"🧥" },
    { q:"Chaqueta/Chamarra", a:"Jacket", e:"🧥" },
    { q:"Suéter/Jersey", a:"Sweater", e:"🧶" },
    { q:"Bufanda", a:"Scarf", e:"🧣" },
    { q:"Guantes", a:"Gloves", e:"🧤" },
    { q:"Vaqueros/Mezclilla", a:"Jeans", e:"👖" },
    { q:"Pantalones cortos", a:"Shorts", e:"🩳" },
    { q:"Falda", a:"Skirt", e:"👗" },
    { q:"Vestido", a:"Dress", e:"👗" },
    { q:"Calcetines/Medias", a:"Socks", e:"🧦" },
    { q:"Sombrero/Gorro", a:"Hat", e:"👒" },
    { q:"Traje", a:"Suit", e:"🤵" },
    { q:"Pijama", a:"Pajamas", e:"🌙" },
    { q:"Joyería", a:"Jewelry", e:"💍" },
    { q:"Anillo", a:"Ring", e:"💍" },
    { q:"Reloj", a:"Watch", e:"⌚" },
    { q:"Bolso", a:"Handbag", e:"👜" },
    { q:"Mochila", a:"Backpack", e:"🎒" },
    { q:"Traje de baño", a:"Swimsuit", e:"🏖️" },
    { q:"Pantuflas", a:"Slippers", e:"🩴" },
    { q:"Sudadera", a:"Hoodie", e:"🥷" },
    { q:"Uniforme", a:"Uniform", e:"👮" },
    { q:"Chaleco", a:"Vest", e:"🦺" },
];
