const VOC_containers = [
    { q:"Una cucharada de...", a:"A Spoonful of", e:"🥄" },
    { q:"Una barra de...", a:"A Bar of", e:"🍫" },
    { q:"Una bolsa de...", a:"A Bag of", e:"🛍️" },
    { q:"Una botella de...", a:"A Bottle of", e:"🍾" },
    { q:"Un tazón de...", a:"A Bowl of", e:"🥣" },
    { q:"Una taza de...", a:"A Cup of", e:"☕" },
    { q:"Un vaso de...", a:"A Glass of", e:"🥛" },
    { q:"Un frasco de...", a:"A Jar of", e:"🫙" },
    { q:"Un paquete de...", a:"A Packet of", e:"📦" },
    { q:"Una caja de...", a:"A Box of", e:"📦" },
    { q:"Una lata de...", a:"A Can of", e:"🥫" },
    { q:"Un cartón de...", a:"A Carton of", e:"🧃" },
    { q:"Un pedazo de...", a:"A Piece of", e:"🍰" },
    { q:"Una rebanada de...", a:"A Slice of", e:"🍕" },
    { q:"Una taza grande de...", a:"A Mug of", e:"☕" },
    { q:"Una taza pequeña de...", a:"A Cup of", e:"🍵" },
    { q:"Una cucharadita de...", a:"A Teaspoon of", e:"🥄" },
    { q:"Una cucharada sopera de...", a:"A Tablespoon of", e:"🥄" },
    { q:"Una porción de...", a:"A Portion of", e:"🍽️" },
    { q:"Una ración de...", a:"A Serving of", e:"🍛" },
    { q:"Una rodaja de...", a:"A Round Slice of", e:"🍋" },
    { q:"Una pieza de fruta", a:"A Piece of Fruit", e:"🍎" },
    { q:"Un paquete grande de...", a:"A Pack of", e:"📦" },
    { q:"Un manojo de...", a:"A Bunch of", e:"🍌" },
    { q:"Un kilo de...", a:"A Kilogram of", e:"⚖️" },
    { q:"Una libra de...", a:"A Pound of", e:"⚖️" },
    { q:"Una gota de...", a:"A Drop of", e:"💧" },
    { q:"Un poco de...", a:"A Little", e:"👌" },
];
