const VOC_food_drinks = [
    { q:"Fruta", a:"Fruit", e:"🍎" },
    { q:"Pera", a:"Pear", e:"🍐" },
    { q:"Manzana", a:"Apple", e:"🍎" },
    { q:"Banana", a:"Banana", e:"🍌" },
    { q:"Limón", a:"Lemon", e:"🍋" },
    { q:"Fresa", a:"Strawberry", e:"🍓" },
    { q:"Naranja", a:"Orange", e:"🍊" },
    { q:"Uvas", a:"Grapes", e:"🍇" },
    { q:"Melón", a:"Melon", e:"🍈" },
    { q:"Sandía", a:"Watermelon", e:"🍉" },
    { q:"Vegetales", a:"Vegetables", e:"🥦" },
    { q:"Pimiento", a:"Pepper", e:"🫑" },
    { q:"Zanahoria", a:"Carrot", e:"🥕" },
    { q:"Frijoles", a:"Beans", e:"🫘" },
    { q:"Tomate", a:"Tomato", e:"🍅" },
    { q:"Pepino", a:"Cucumber", e:"🥒" },
    { q:"Papa", a:"Potato", e:"🥔" },
    { q:"Champiñones/Hongos", a:"Mushrooms", e:"🍄" },
    { q:"Guisantes/Arvejas", a:"Peas", e:"🫛" },
    { q:"Repollo", a:"Cabbage", e:"🥬" },
    { q:"Cebolla", a:"Onion", e:"🧅" },
    { q:"Maíz", a:"Corn", e:"🌽" },
    { q:"Cereales/Granos", a:"Grains", e:"🌾" },
    { q:"Pasta", a:"Pasta", e:"🍝" },
    { q:"Pan", a:"Bread", e:"🍞" },
    { q:"Cereal", a:"Cereal", e:"🥣" },
    { q:"Arroz", a:"Rice", e:"🍚" },
    { q:"Proteínas", a:"Proteins", e:"🥩" },
    { q:"Lácteos", a:"Dairy", e:"🥛" },
    { q:"Carne", a:"Meat", e:"🍖" },
    { q:"Carne de res", a:"Beef", e:"🥩" },
    { q:"Pollo", a:"Chicken", e:"🍗" },
    { q:"Pescado", a:"Fish", e:"🐟" },
    { q:"Huevo", a:"Egg", e:"🥚" },
    { q:"Queso", a:"Cheese", e:"🧀" },
    { q:"Yogur", a:"Yogurt", e:"🥛" },
    { q:"Helado", a:"Ice Cream", e:"🍨" },
    { q:"Snacks", a:"Snacks", e:"🍿" },
    { q:"Pastel/Torta", a:"Cake", e:"🎂" },
    { q:"Ensalada", a:"Salad", e:"🥗" },
    { q:"Papas fritas", a:"French Fries", e:"🍟" },
    { q:"Sopa", a:"Soup", e:"🍲" },
    { q:"Galletas", a:"Cookies", e:"🍪" },
    { q:"Papas de bolsa", a:"Potato Chips", e:"🥔" },
    { q:"Hamburguesa", a:"Hamburger", e:"🍔" },
    { q:"Pizza", a:"Pizza", e:"🍕" },
    { q:"Bebidas", a:"Drinks", e:"🥤" },
    { q:"Agua", a:"Water", e:"💧" },
    { q:"Café", a:"Coffee", e:"☕" },
    { q:"Té", a:"Tea", e:"🍵" },
    { q:"Jugo", a:"Juice", e:"🧃" },
    { q:"Refresco de cola", a:"Cola", e:"🥤" },
    { q:"Leche", a:"Milk", e:"🥛" },
    { q:"Chocolate caliente", a:"Hot Chocolate", e:"🍫" },
];
