const VOC_hobbies = [
    { q:"Coleccionar", a:"Collect", e:"📦" },
    { q:"Jugar", a:"Play", e:"🎮" },
    { q:"Hacer/Crear", a:"Make", e:"🛠️" },
    { q:"Coser", a:"Sew", e:"🧵" },
    { q:"Tejer", a:"Knit", e:"🧶" },
    { q:"Cantar", a:"Sing", e:"🎤" },
    { q:"Bailar", a:"Dance", e:"💃" },
    { q:"Tomar fotos", a:"Take photos", e:"📸" },
    { q:"Escribir", a:"Write", e:"✍️" },
    { q:"Pintar", a:"Paint", e:"🎨" },
    { q:"Dibujar", a:"Draw", e:"✏️" },
    { q:"Hornear/Repostería", a:"Bake", e:"🧁" },
    { q:"Leer", a:"Read", e:"📚" },
    { q:"Escuchar música", a:"Listen to music", e:"🎧" },
    { q:"Ver películas", a:"Watch movies", e:"🎬" },
    { q:"Ver televisión", a:"Watch TV", e:"📺" },
    { q:"Jugar videojuegos", a:"Play video games", e:"🎮" },
    { q:"Nadar", a:"Swim", e:"🏊" },
    { q:"Correr", a:"Run", e:"🏃" },
    { q:"Caminar", a:"Walk", e:"🚶" },
    { q:"Andar en bicicleta", a:"Ride a bike", e:"🚴" },
    { q:"Acampar", a:"Camp", e:"🏕️" },
    { q:"Pescar", a:"Fish", e:"🎣" },
    { q:"Viajar", a:"Travel", e:"✈️" },
    { q:"Cocinar", a:"Cook", e:"👨‍🍳" },
    { q:"Jardinería", a:"Garden", e:"🌱" },
    { q:"Tocar guitarra", a:"Play the guitar", e:"🎸" },
    { q:"Tocar piano", a:"Play the piano", e:"🎹" },
    { q:"Fotografía", a:"Photography", e:"📷" },
    { q:"Coleccionar monedas", a:"Collect coins", e:"🪙" },
    { q:"Coleccionar estampillas", a:"Collect stamps", e:"📮" },
    { q:"Hacer ejercicio", a:"Exercise", e:"💪" },
];
