const VOC_inventions = [
    { q:"Congelador", a:"Freezer", e:"🧊" },
    { q:"Televisión", a:"TV", e:"📺" },
    { q:"Teléfono inteligente", a:"Smartphone", e:"📱" },
    { q:"Refrigerador", a:"Fridge", e:"🧊" },
    { q:"Cámara digital", a:"Digital Camera", e:"📷" },
    { q:"Reproductor de casetes", a:"Cassette Player", e:"📼" },
    { q:"Lavavajillas", a:"Dishwasher", e:"🍽️" },
    { q:"Secadora", a:"Clothes Dryer", e:"👕" },
    { q:"Reproductor de DVD", a:"DVD Player", e:"💿" },
    { q:"Televisión blanco y negro", a:"Black-and-White TV", e:"📺" },
    { q:"Computadora portátil", a:"Laptop", e:"💻" },
    { q:"GPS", a:"GPS", e:"🛰️" },
    { q:"Tostadora", a:"Toaster", e:"🍞" },
    { q:"Reproductor de video", a:"Video Player", e:"📹" },
    { q:"Microondas", a:"Microwave", e:"📡" },
    { q:"Reproductor de CD", a:"CD Player", e:"💿" },
    { q:"Aspiradora", a:"Vacuum Cleaner", e:"🧹" },
    { q:"Lavadora", a:"Washing Machine", e:"🧺" },
    { q:"Computadora", a:"Computer", e:"🖥️" },
    { q:"Tablet", a:"Tablet", e:"📲" },
    { q:"Impresora", a:"Printer", e:"🖨️" },
    { q:"Audífonos", a:"Headphones", e:"🎧" },
    { q:"Altavoz", a:"Speaker", e:"🔊" },
    { q:"Control remoto", a:"Remote Control", e:"🎮" },
    { q:"Reloj inteligente", a:"Smartwatch", e:"⌚" },
    { q:"Aire acondicionado", a:"Air Conditioner", e:"❄️" },
    { q:"Ventilador", a:"Fan", e:"🌀" },
    { q:"Cafetera", a:"Coffee Maker", e:"☕" },
    { q:"Licuadora", a:"Blender", e:"🥤" },
    { q:"Horno eléctrico", a:"Electric Oven", e:"🔥" },
];
