const VOC_jobs = [
    { q:"Peluquero", a:"Hairdresser", e:"💇" },
    { q:"Guía turístico", a:"Tour Guide", e:"🗺️" },
    { q:"Doctor/Doctora", a:"Doctor", e:"🩺" },
    { q:"Electricista", a:"Electrician", e:"🔌" },
    { q:"Maestro/Maestra", a:"Teacher", e:"👨‍🏫" },
    { q:"Taxista", a:"Taxi Driver", e:"🚕" },
    { q:"Dentista", a:"Dentist", e:"🦷" },
    { q:"Auxiliar de vuelo", a:"Flight Attendant", e:"✈️" },
    { q:"Cantante", a:"Singer", e:"🎤" },
    { q:"Mecánico", a:"Mechanic", e:"🔧" },
    { q:"Enfermero/Enfermera", a:"Nurse", e:"💉" },
    { q:"Abogado/Abogada", a:"Lawyer", e:"⚖️" },
    { q:"Camarero", a:"Waiter", e:"🍽️" },
    { q:"Camarera", a:"Waitress", e:"🍽️" },
    { q:"Recepcionista", a:"Receptionist", e:"🛎️" },
    { q:"Empresario", a:"Businessperson", e:"💼" },
    { q:"Contador", a:"Accountant", e:"📊" },
    { q:"Trabajador de construcción", a:"Construction Worker", e:"👷" },
    { q:"Cocinero", a:"Chef", e:"👨‍🍳" },
    { q:"Vendedor", a:"Salesclerk", e:"🛒" },
    { q:"Policía", a:"Police Officer", e:"👮" },
    { q:"Bombero", a:"Firefighter", e:"👨‍🚒" },
    { q:"Ingeniero", a:"Engineer", e:"👨‍💻" },
    { q:"Programador", a:"Programmer", e:"💻" },
    { q:"Arquitecto", a:"Architect", e:"📐" },
    { q:"Diseñador", a:"Designer", e:"🎨" },
    { q:"Fotógrafo", a:"Photographer", e:"📸" },
    { q:"Periodista", a:"Journalist", e:"📰" },
    { q:"Actor", a:"Actor", e:"🎭" },
    { q:"Actriz", a:"Actress", e:"🎭" },
    { q:"Músico", a:"Musician", e:"🎸" },
    { q:"Veterinario", a:"Veterinarian", e:"🐶" },
    { q:"Farmacéutico", a:"Pharmacist", e:"💊" },
    { q:"Piloto", a:"Pilot", e:"🛩️" },
    { q:"Agricultor", a:"Farmer", e:"🚜" },
    { q:"Panadero", a:"Baker", e:"🥖" },
    { q:"Cajero", a:"Cashier", e:"💵" },
    { q:"Secretario", a:"Secretary", e:"📋" },
    { q:"Gerente", a:"Manager", e:"📈" },
    { q:"Estudiante", a:"Student", e:"🎓" },
];
