const VOC_life_stages = [
    { q:"Nacer", a:"Be Born", e:"👶" },
    { q:"Empezar la escuela", a:"Start School", e:"🎒" },
    { q:"Terminar la escuela", a:"Finish School", e:"🎓" },
    { q:"Ir a la universidad", a:"Go to College", e:"🏫" },
    { q:"Conseguir un trabajo", a:"Get a Job", e:"💼" },
    { q:"Obtener un título universitario", a:"Get a Degree", e:"🎓" },
    { q:"Conocer a alguien", a:"Meet Someone", e:"🤝" },
    { q:"Casarse", a:"Get Married", e:"💍" },
    { q:"Tener un bebé", a:"Have a Baby", e:"👶" },
    { q:"Divorciarse", a:"Get Divorced", e:"💔" },
    { q:"Jubilarse", a:"Retire", e:"🏖️" },
    { q:"Morir", a:"Die", e:"🕊️" },
    { q:"Ser niño", a:"Be a Child", e:"🧒" },
    { q:"Ser adolescente", a:"Be a Teenager", e:"🧑" },
    { q:"Convertirse en adulto", a:"Become an Adult", e:"🧑‍💼" },
    { q:"Mudarse de casa", a:"Move House", e:"🏠" },
    { q:"Aprender a conducir", a:"Learn to Drive", e:"🚗" },
    { q:"Comprar una casa", a:"Buy a House", e:"🏡" },
    { q:"Tener hijos", a:"Have Children", e:"👨‍👩‍👧‍👦" },
    { q:"Cambiar de trabajo", a:"Change Jobs", e:"🔄" },
    { q:"Viajar al extranjero", a:"Travel Abroad", e:"✈️" },
    { q:"Cumplir años", a:"Have a Birthday", e:"🎂" },
    { q:"Graduarse", a:"Graduate", e:"🎓" },
    { q:"Envejecer", a:"Grow Old", e:"👴" },
];
