const VOC_places_city = [
    { q:"Apartamento", a:"Apartment Building", e:"🏢" },
    { q:"Puente", a:"Bridge", e:"🌉" },
    { q:"Catedral", a:"Cathedral", e:"⛪" },
    { q:"Sala de conciertos", a:"Concert Hall", e:"🎼" },
    { q:"Biblioteca", a:"Library", e:"📚" },
    { q:"Mercado", a:"Market", e:"🛒" },
    { q:"Monumento", a:"Monument", e:"🗿" },
    { q:"Mezquita", a:"Mosque", e:"🕌" },
    { q:"Edificio de oficinas", a:"Office Building", e:"🏢" },
    { q:"Parque", a:"Park", e:"🌳" },
    { q:"Rascacielos", a:"Skyscraper", e:"🏙️" },
    { q:"Plaza", a:"Square", e:"⛲" },
    { q:"Estadio", a:"Stadium", e:"🏟️" },
    { q:"Teatro", a:"Theater", e:"🎭" },
    { q:"Banco", a:"Bank", e:"🏦" },
    { q:"Hospital", a:"Hospital", e:"🏥" },
    { q:"Escuela", a:"School", e:"🏫" },
    { q:"Universidad", a:"University", e:"🎓" },
    { q:"Restaurante", a:"Restaurant", e:"🍽️" },
    { q:"Cafetería", a:"Coffee Shop", e:"☕" },
    { q:"Hotel", a:"Hotel", e:"🏨" },
    { q:"Supermercado", a:"Supermarket", e:"🛒" },
    { q:"Estación de policía", a:"Police Station", e:"👮" },
    { q:"Estación de bomberos", a:"Fire Station", e:"🚒" },
    { q:"Aeropuerto", a:"Airport", e:"✈️" },
    { q:"Estación de tren", a:"Train Station", e:"🚆" },
    { q:"Parada de autobús", a:"Bus Stop", e:"🚏" },
    { q:"Museo", a:"Museum", e:"🏛️" },
    { q:"Iglesia", a:"Church", e:"⛪" },
    { q:"Farmacia", a:"Pharmacy", e:"💊" },
    { q:"Centro comercial", a:"Shopping Mall", e:"🛍️" },
    { q:"Gasolinera", a:"Gas Station", e:"⛽" },
    { q:"Oficina de correos", a:"Post Office", e:"📮" },
    { q:"Cine", a:"Movie Theater", e:"🎬" },
    { q:"Zoológico", a:"Zoo", e:"🦁" },
    { q:"Acuario", a:"Aquarium", e:"🐠" },
    { q:"Fuente", a:"Fountain", e:"⛲" },
    { q:"Ayuntamiento", a:"City Hall", e:"🏛️" },
];
