const VOC_weather = [
    { q:"Primavera", a:"Spring", e:"🌸" },
    { q:"Verano", a:"Summer", e:"☀️" },
    { q:"Otoño", a:"Fall", e:"🍂" },
    { q:"Invierno", a:"Winter", e:"❄️" },
    { q:"Está lloviendo", a:"It's raining", e:"🌧️" },
    { q:"Está lluvioso", a:"It's rainy", e:"☔" },
    { q:"Está nevando", a:"It's snowing", e:"🌨️" },
    { q:"Está nevado", a:"It's snowy", e:"❄️" },
    { q:"Hace calor", a:"It's hot", e:"🥵" },
    { q:"Está cálido", a:"It's warm", e:"🌤️" },
    { q:"Hace frío", a:"It's cold", e:"🥶" },
    { q:"Hace mucho frío", a:"It's very cold", e:"🧊" },
    { q:"Está húmedo", a:"It's humid", e:"💧" },
    { q:"Está mojado", a:"It's wet", e:"💦" },
    { q:"Está soleado", a:"It's sunny", e:"☀️" },
    { q:"Hace viento", a:"It's windy", e:"💨" },
    { q:"Está nublado", a:"It's cloudy", e:"☁️" },
    { q:"Está congelado", a:"It's icy", e:"🧊" },
    { q:"Hay tormenta", a:"There's a storm", e:"⛈️" },
    { q:"Hay truenos", a:"There's thunder", e:"⚡" },
    { q:"Hay relámpagos", a:"There's lightning", e:"⚡" },
    { q:"Hay niebla", a:"It's foggy", e:"🌫️" },
    { q:"Está despejado", a:"It's clear", e:"🌞" },
    { q:"Hace buen tiempo", a:"The weather is nice", e:"😊" },
    { q:"Hace mal tiempo", a:"The weather is bad", e:"😞" },
    { q:"Arcoíris", a:"Rainbow", e:"🌈" },
    { q:"Temperatura", a:"Temperature", e:"🌡️" },
    { q:"Sol", a:"Sun", e:"☀️" },
    { q:"Lluvia", a:"Rain", e:"🌧️" },
    { q:"Nieve", a:"Snow", e:"❄️" },
    { q:"Viento", a:"Wind", e:"💨" },
    { q:"Nube", a:"Cloud", e:"☁️" },
    { q:"Auroras boreales", a:"Northern Lights", e:"🌌" },
    { q:"Auroras australes", a:"Southern Lights", e:"🌌" },
    { q:"Eclipse solar", a:"Solar Eclipse", e:"🌞" },
    { q:"Eclipse lunar", a:"Lunar Eclipse", e:"🌕" },
    { q:"Tornado", a:"Tornado", e:"🌪️" },
    { q:"Huracán", a:"Hurricane", e:"🌀" },
    { q:"Granizo", a:"Hail", e:"🧊" },
    { q:"Ola de calor", a:"Heat Wave", e:"🌡️" },
    { q:"Sequía", a:"Drought", e:"🏜️" },
    { q:"Inundación", a:"Flood", e:"🌊" },
];
